# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: asset3
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:
      #- image: circleci/mysql:latest
      #  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
      #  environment:
      #    MYSQL_USER: root
      #    MYSQL_ALLOW_EMPTY_PASSWORD: true
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt install -y mysql-server
      - run: sudo apt install -y mysql-client
      - run: sudo service mysql start

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: mysql -h 127.0.0.1 -u root -e "create databse asset3;"
      - run: cp .env.exmaple .env
      - run: php artisan migrate
      - run: vendor/bin/phpunit